version: '3'
 
services:
    server:
        image: brgelab/snptest_container:latest     
        hostname: server
        ports:
            - "2223:22"
        environment:
                - MASTER_USER=${SSH_MASTER_USER}
                - MASTER_PASS=${SSH_MASTER_PASS}
        volumes:
            - ./data:/home/master
